### ISSUE TITLE
Замечания по работе #5.2

### ISSUE THREAD

**Issue by Und3rMySk1n** [BlackFox101/Web-development#2]
- [x] div с классом header_lists получился нулевой высоты, забыл сбросить поток документа после использования плавающих блоков.
- [x] img_qoutes - Нулевой высоты
- [x] img.porter - указаны стили float и position: absolute. Как только мы делаем блок абсолютным, float'ы перестают работать, так что этот стиль можно удалить.
- [x] стиль у класса .me не применился - там опечатка

- [x] тут не обязательно задавать ссылку (a), можно проставить id="favourite_films" прямо в тег h2. И якорь из верхнего меню все так же будет работать.
```
<h2 class="info_film"><a id="favorite_films"></a> Любимые фильмы</h2>
```

- [x] не сброшен поток для плавающих элементов внутри блока .films, из-за чего ему пришлось выставить высоту в пикселях. Вообще, по всей странице ни разу не сбрасывается поток документа с помощью clear, это надо поправить. Иначе поведение сайта будет непредсказуемым, а когда начнется адаптивность - станет совсем плохо.
- [x] нет наведенного состояния у ссылки "Напиши мне" и у кнопки "Все фильмы". В дизайне они есть, на скрытых слоях.
- [x] В качестве отступов у нас используются пробелы, а у тебя - табы. Надо исправить.
- [x] В CSS та же история, нужно сделать все отступы пробелами.

**Comment by BlackFox101** [comment]
Все исправил

**Comment by Und3rMySk1n** [comment]
- [x] img_qoutes - все еще нулевой высоты, если не задать ее в CSS. Поставить фиксированную высоту с помощью свойства height - плохой выход, если вдруг поменяется контент - придется снова лезть в свойства и выставлять новое значение. Вместо этого предлагаю сбросить поток документа после плавающих элементов внутри img_qoutes. А картинку не делать абсолютной, потому что абсолютные блоки "выпадают" из потока документа и не позволяют родительскому блоку занять высоту контента.

**Comment by BlackFox101** [comment]
Cбросил поток документа после плавающих элементов внутри img_qoutes. Картинку оставил абсолютной , но .img_qoutes сделал relative
