### ISSUE TITLE
Замечания по работе #6 (фронтенд)

### ISSUE THREAD

**Issue by Und3rMySk1n** [BlackFox101/Web-development#3]
- [x] не надо складывать каждый input в тег `<p>`. Этот тег - для абзацев, то есть определенного количества текста, а у тебя в форме он используется не по назначению.
- [x] почему-то у поля ввода имени стоит title="email". В итоге при наведении на это поле всплывает подсказка, что это email, а это неправда.
- [x] есть ошибка валидации
- [x] надо сделать так, чтобы при наведении на кликабельные элементы (кнопка отправки формы, select, чекбоксы и их лейбл) курсор менялся на "палец". Для этого есть свойство cursor: pointer. Пользователь должен знать, что он может выбрать и куда может нажать, палец для него как подсказка.
- [x] у полей формы есть обычное состояние, наведенное и фокусное. В обычном состоянии цвет бордера #c9c9c9, в наведенном - #a6a6a6, а в фокусном - зеленый (#15a98c). Надо чтобы на странице все это было.
- [x] стрелка "вниз" у select'а в дизайне нестандартная. Надо заменить стандартную стрелку на дизайнерскую.
- [x] если ввести много текста в поле ввода имени или email, текст будет задевать правый край поля ввода. Чтобы этого не было - надо добавлять padding не только слева, но и справа.
- [x] заголовок "напиши мне" в дизайне заглавными буквами. И его цвет в дизайне не такой, как на странице.

**Comment by BlackFox101** [comment]
Исправил
